server:
  port : 8086

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/microservice-rating
      username: root
      password: rootroot
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect


    application:
      name: RATING-SERVICE
    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka

